# -*- coding: utf-8 -*-
"""HAP (TRACK 1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wZAmSudo-DPXyon8UdKfxPJch98c3vYB
"""

import json
import pandas as pd

with open("/content/drive/MyDrive/sample_candidates", "r") as f:
    data = json.load(f)

print(type(data))
print(len(data))
print(data[0].keys())

from pprint import pprint

pprint(data[0])

import os

file_path = "/content/drive/MyDrive/sample_candidates"
size_mb = os.path.getsize(file_path) / (1024*1024)
print(f"{file_path} size: {size_mb:.2f} MB")

print(data[0]["profile"])

print(data[0]["skills"])

JD_SKILLS = {
    "python",
    "retrieval",
    "ranking",
    "embeddings",
    "vector database",
    "faiss",
    "pinecone",
    "weaviate",
    "qdrant",
    "machine learning",
    "llm",
    "recommendation",
    "aws",
    "nlp"
}

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

model = SentenceTransformer('all-MiniLM-L6-v2')

jd_description = (
    "We are looking for a Machine Learning Engineer with strong skills in retrieval, ranking, "
    "embeddings, and vector databases (Faiss, Pinecone, Weaviate, Qdrant). "
    "Experience with LLMs, recommendation systems, AWS, and NLP is highly valued. "
    "Proficiency in Python is essential."
)

jd_embedding = model.encode(jd_description)

def skill_score(candidate):
    candidate_skills = set(
        skill["name"].lower() for skill in candidate["skills"]
    )
    matches = len(candidate_skills.intersection(JD_SKILLS))
    return matches / len(JD_SKILLS)

score = skill_score(data[0])
print(score)

import json

with open("/content/drive/MyDrive/sample_candidates", "r") as f:
    data = json.load(f)

print(data[0]["redrob_signals"])

print(skill_score(data[0]))

from pprint import pprint

pprint(data[0]["redrob_signals"])

def experience_score(candidate):

    years = candidate["profile"].get(
        "years_of_experience", 0
    )

    if years >= 6:
        return 1.0
    elif years >= 4:
        return 0.8
    elif years >= 2:
        return 0.6
    else:
        return 0.3

print(experience_score(data[0]))

print(data[0]["redrob_signals"].keys())

def behavioral_score(candidate):

    signals = candidate["redrob_signals"]

    score = 0


    if signals.get("open_to_work_flag", False):
        score += 20


    score += signals.get(
        "profile_completeness_score", 0
    ) / 5


    score += signals.get(
        "recruiter_response_rate", 0
    ) * 20


    score += signals.get(
        "offer_acceptance_rate", 0
    ) * 20


    score += signals.get(
        "github_activity_score", 0
    )


    if signals.get("verified_email", False):
        score += 5

    if signals.get("verified_phone", False):
        score += 5

    return score / 100

def quality_penalty(candidate):

    signals = candidate["redrob_signals"]

    penalty = 0

    if signals.get(
        "profile_completeness_score",0
    ) < 50:
        penalty += 0.15

    if not signals.get(
        "verified_email",False
    ):
        penalty += 0.05

    if not signals.get(
        "verified_phone",False
    ):
        penalty += 0.05

    return penalty

def final_score(candidate):

    return (
        0.40 * skill_score(candidate) +
        0.25 * experience_score(candidate) +
        0.35 * behavioral_score(candidate)
    )

print(f"Final Score for candidate 0: {final_score(data[0])}")

print(behavioral_score(data[0]))

print(final_score(data[0]))

ranked_candidates = sorted(
    data,
    key=final_score,
    reverse=True
)

print("Top 10 Candidates by Final Score:")
for i, candidate in enumerate(ranked_candidates[:10], start=1):
    print(
        f"{i}. Candidate ID: {candidate['candidate_id']}, Final Score: {round(final_score(candidate), 4)}"
    )

print("All Candidates by Final Score:")
for i, candidate in enumerate(ranked_candidates, start=1):
    print(
        f"{i}. Candidate ID: {candidate['candidate_id']}, Final Score: {round(final_score(candidate), 4)}"
    )

def semantic_score(candidate):

    text = ""

    text += candidate["profile"].get("summary", "")

    for skill in candidate["skills"]:
        text += " " + skill["name"]

    embedding = model.encode(text)

    score = cosine_similarity(
        [jd_embedding],
        [embedding]
    )[0][0]

    return float(score)

def final_score(candidate):

    return (
        0.35 * semantic_score(candidate) +
        0.25 * skill_score(candidate) +
        0.15 * experience_score(candidate) +
        0.25 * behavioral_score(candidate) -
        quality_penalty(candidate)
    )

all_candidates = data

ranked_candidates = sorted(
    all_candidates,
    key=final_score,
    reverse=True
)

print("Top Candidates by Final Score (with Quality Penalty):")
for i, candidate in enumerate(ranked_candidates[:100], start=1):
    print(
        f"{i}. Candidate ID: {candidate['candidate_id']}, Final Score: {round(final_score(candidate), 4)}"
    )

def explanation(candidate):

    return {
        "candidate_id":
            candidate["candidate_id"],

        "skill_score":
            round(skill_score(candidate),3),

        "experience_score":
            round(experience_score(candidate),3),

        "behavior_score":
            round(behavioral_score(candidate),3),

        "semantic_score":
            round(semantic_score(candidate),3)
    }

print(explanation(ranked_candidates[0]))

import pandas as pd

submission_rows = []

for rank, candidate in enumerate(ranked_candidates[:100], start=1):

    score = round(final_score(candidate), 4)

    reasoning = (
        f"{candidate['profile'].get('current_title','Professional')} "
        f"with {candidate['profile'].get('years_of_experience',0):.1f} yrs experience; "
        f"matched key skills; strong behavioral signals"
    )

    submission_rows.append({
        "candidate_id": candidate["candidate_id"],
        "rank": rank,
        "score": score,
        "reasoning": reasoning
    })

submission = pd.DataFrame(submission_rows)

submission.to_csv(
    "/content/drive/MyDrive/submission.csv",
    index=False
)

print("submission.csv created successfully")
submission.head()

submission = pd.read_csv(
    "/content/drive/MyDrive/submission.csv"
)

print(submission.head())
print(submission.shape)

!python "/content/drive/MyDrive/validate_submission.py" "/content/drive/MyDrive/submission.csv"